# Generated by Django 6.0.7 on 2026-07-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=30, unique=True, verbose_name='NIDN')),
                ('nama', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Dosen',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Laboratorium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_lab', models.CharField(max_length=20, unique=True)),
                ('nama_lab', models.CharField(max_length=100)),
                ('gedung', models.CharField(blank=True, max_length=50)),
                ('lantai', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Laboratorium',
                'ordering': ['kode_lab'],
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('program_studi', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mahasiswa',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Kunci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kunci', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Tersedia', 'Tersedia'), ('Dipinjam', 'Dipinjam')], default='Tersedia', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunci', to='master_data.laboratorium')),
            ],
            options={
                'verbose_name_plural': 'Kunci',
                'ordering': ['laboratorium', 'nomor_kunci'],
                'unique_together': {('laboratorium', 'nomor_kunci')},
            },
        ),
    ]
