# Generated by Django 6.0.7 on 2026-08-07 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunci',
            name='laboratorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunci', to='master_data.laboratorium', verbose_name='Ruangan'),
        ),
        migrations.AlterField(
            model_name='laboratorium',
            name='nama_lab',
            field=models.CharField(max_length=100, verbose_name='Nama Ruangan'),
        ),
    ]
