# Generated by Django 6.0.7 on 2026-07-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peminjaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pinjam', models.DateField(auto_now_add=True)),
                ('jam_pinjam', models.TimeField()),
                ('tanggal_kembali', models.DateField(blank=True, null=True)),
                ('jam_kembali', models.TimeField(blank=True, null=True)),
                ('keperluan', models.TextField()),
                ('status', models.CharField(choices=[('Dipinjam', 'Dipinjam'), ('Dikembalikan', 'Dikembalikan')], default='Dipinjam', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='master_data.dosen')),
                ('kunci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='master_data.kunci')),
                ('laboratorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='master_data.laboratorium')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='master_data.mahasiswa')),
            ],
            options={
                'verbose_name_plural': 'Peminjaman',
                'ordering': ['-created_at'],
            },
        ),
    ]
