# Generated by Django 6.0.7 on 2026-08-07 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_kunci_laboratorium_alter_laboratorium_nama_lab'),
        ('transaction', '0002_alter_peminjaman_tanggal_pinjam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='kunci',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peminjaman', to='master_data.kunci', verbose_name='Kunci'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='laboratorium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peminjaman', to='master_data.laboratorium', verbose_name='Ruangan'),
        ),
    ]
