# Generated by Django 6.0.7 on 2026-08-07 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_alter_kunci_laboratorium_alter_laboratorium_nama_lab'),
        ('transaction', '0003_alter_peminjaman_kunci_alter_peminjaman_laboratorium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peminjaman',
            name='dosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peminjaman', to='master_data.dosen'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='laboratorium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peminjaman', to='master_data.laboratorium', verbose_name='Ruangan'),
        ),
        migrations.AlterField(
            model_name='peminjaman',
            name='mahasiswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peminjaman', to='master_data.mahasiswa'),
        ),
    ]
