# Generated by Django 6.0.7 on 2026-08-06 00:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenanggungJawab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('telepon', models.CharField(blank=True, max_length=30)),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='penanggung_jawab', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Penanggung Jawab',
                'ordering': ['nama_lengkap'],
            },
        ),
    ]
