# Generated by Django 6.0.7 on 2026-08-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('penanggung_jawab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='authentication.penanggungjawab')),
            ],
            options={
                'verbose_name_plural': 'Device Tokens',
            },
        ),
    ]
