# Generated by Django 6.0.7 on 2026-08-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifikasi',
            name='status',
            field=models.CharField(choices=[('Menunggu', 'Menunggu'), ('Terkirim', 'Terkirim'), ('Gagal', 'Gagal')], default='Menunggu', max_length=10),
        ),
    ]
